-- BondDesk OMS schema (PostgreSQL). Reference data is loaded by DataSeeder at startup,
-- so this migration owns structure only. Kept in sync with the JPA entities, which are
-- validated against it (spring.jpa.hibernate.ddl-auto=validate) under the postgres profile.

CREATE TABLE security (
    cusip         VARCHAR(9)     PRIMARY KEY,
    isin          VARCHAR(12),
    description   VARCHAR(255)   NOT NULL,
    issuer        VARCHAR(255)   NOT NULL,
    coupon_rate   NUMERIC(7, 4)  NOT NULL,
    maturity_date DATE           NOT NULL,
    face_value    NUMERIC(19, 2) NOT NULL,
    currency      VARCHAR(3)     NOT NULL,
    sector        VARCHAR(255)   NOT NULL,
    rating        VARCHAR(255)   NOT NULL,
    clean_price   NUMERIC(9, 4)  NOT NULL,
    restricted    BOOLEAN        NOT NULL
);

CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ref       VARCHAR(36)    NOT NULL UNIQUE,
    cusip           VARCHAR(9)     NOT NULL REFERENCES security (cusip),
    portfolio       VARCHAR(255)   NOT NULL,
    trader          VARCHAR(255)   NOT NULL,
    side            VARCHAR(255)   NOT NULL,
    order_type      VARCHAR(255)   NOT NULL,
    time_in_force   VARCHAR(255)   NOT NULL,
    quantity        NUMERIC(19, 2) NOT NULL,
    limit_price     NUMERIC(9, 4),
    status          VARCHAR(255)   NOT NULL,
    filled_quantity NUMERIC(19, 2) NOT NULL,
    avg_fill_price  NUMERIC(9, 4),
    status_reason   VARCHAR(500),
    created_at      TIMESTAMPTZ    NOT NULL,
    updated_at      TIMESTAMPTZ    NOT NULL,
    version         BIGINT
);

CREATE TABLE execution (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT         NOT NULL REFERENCES orders (id),
    quantity    NUMERIC(19, 2) NOT NULL,
    price       NUMERIC(9, 4)  NOT NULL,
    venue       VARCHAR(16)    NOT NULL,
    executed_at TIMESTAMPTZ    NOT NULL
);

CREATE TABLE positions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio    VARCHAR(255)   NOT NULL,
    cusip        VARCHAR(9)     NOT NULL REFERENCES security (cusip),
    net_quantity NUMERIC(19, 2) NOT NULL,
    avg_cost     NUMERIC(9, 4)  NOT NULL,
    updated_at   TIMESTAMPTZ    NOT NULL,
    version      BIGINT,
    CONSTRAINT uq_position_portfolio_cusip UNIQUE (portfolio, cusip)
);

CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_portfolio ON orders (portfolio);
CREATE INDEX idx_execution_order_id ON execution (order_id);
CREATE INDEX idx_positions_portfolio ON positions (portfolio);
