-- Transactional outbox for order-lifecycle events. Rows are inserted in the same transaction as the
-- order change (atomic with the state they describe), then relayed to Kafka and stamped published_at.
CREATE TABLE outbox_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id VARCHAR(255) NOT NULL,   -- order reference; also the Kafka message key
    event_type   VARCHAR(64)  NOT NULL,
    topic        VARCHAR(255) NOT NULL,
    payload      TEXT         NOT NULL,   -- serialized OrderEvent JSON
    created_at   TIMESTAMPTZ  NOT NULL,
    published_at TIMESTAMPTZ,             -- NULL until the broker acks
    attempts     INTEGER      NOT NULL DEFAULT 0
);

-- The relay repeatedly scans for the oldest unpublished rows; this index keeps that scan cheap.
CREATE INDEX ix_outbox_unpublished ON outbox_event (published_at, id);
