-- Application users + their roles, for JWT-based authentication and RBAC.
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,   -- BCrypt (60 chars)
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE user_role (
    user_id BIGINT      NOT NULL REFERENCES app_user (id),
    role    VARCHAR(16) NOT NULL,
    PRIMARY KEY (user_id, role)
);
