-- CI fixture: stand up the OMS source tables and load a small, deterministic dataset so
-- `dbt build` can run the models and their data-quality tests without the live OMS.
--
-- The DDL below mirrors backend/src/main/resources/db/migration/V1__schema.sql (the tables dbt
-- reads). In production these tables are owned by the OMS and populated by the application; here
-- they are a fixture. The data is intentionally shaped to exercise every KPI branch: fully filled,
-- partially filled, rejected, cancelled, and still-open orders, multi-fill orders, and several
-- venues and trade dates — while reconciling exactly (sum of fills == filled_quantity).

CREATE TABLE IF NOT EXISTS security (
    cusip         VARCHAR(9)     PRIMARY KEY,
    isin          VARCHAR(12),
    description   VARCHAR(255)   NOT NULL,
    issuer        VARCHAR(255)   NOT NULL,
    coupon_rate   NUMERIC(7, 4)  NOT NULL,
    maturity_date DATE           NOT NULL,
    face_value    NUMERIC(19, 2) NOT NULL,
    currency      VARCHAR(3)     NOT NULL,
    sector        VARCHAR(255)   NOT NULL,
    rating        VARCHAR(255)   NOT NULL,
    clean_price   NUMERIC(9, 4)  NOT NULL,
    restricted    BOOLEAN        NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ref       VARCHAR(36)    NOT NULL UNIQUE,
    cusip           VARCHAR(9)     NOT NULL REFERENCES security (cusip),
    portfolio       VARCHAR(255)   NOT NULL,
    trader          VARCHAR(255)   NOT NULL,
    side            VARCHAR(255)   NOT NULL,
    order_type      VARCHAR(255)   NOT NULL,
    time_in_force   VARCHAR(255)   NOT NULL,
    quantity        NUMERIC(19, 2) NOT NULL,
    limit_price     NUMERIC(9, 4),
    status          VARCHAR(255)   NOT NULL,
    filled_quantity NUMERIC(19, 2) NOT NULL,
    avg_fill_price  NUMERIC(9, 4),
    status_reason   VARCHAR(500),
    created_at      TIMESTAMPTZ    NOT NULL,
    updated_at      TIMESTAMPTZ    NOT NULL,
    version         BIGINT
);

CREATE TABLE IF NOT EXISTS execution (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT         NOT NULL REFERENCES orders (id),
    quantity    NUMERIC(19, 2) NOT NULL,
    price       NUMERIC(9, 4)  NOT NULL,
    venue       VARCHAR(16)    NOT NULL,
    executed_at TIMESTAMPTZ    NOT NULL
);

TRUNCATE execution, orders, security RESTART IDENTITY CASCADE;

INSERT INTO security (cusip, isin, description, issuer, coupon_rate, maturity_date, face_value, currency, sector, rating, clean_price, restricted) VALUES
  ('912828XG8', 'US912828XG84', 'US Treasury 2.5% 2030',  'US TREASURY',    2.5000, '2030-05-15', 1000.00, 'USD', 'GOVERNMENT', 'AAA', 98.5000, false),
  ('037833EM5', 'US037833EM50', 'Apple Inc 3.25% 2029',   'APPLE INC',      3.2500, '2029-02-23', 1000.00, 'USD', 'TECHNOLOGY', 'AA',  101.2500, false),
  ('594918BW3', 'US594918BW34', 'Microsoft 2.4% 2031',    'MICROSOFT CORP', 2.4000, '2031-08-08', 1000.00, 'USD', 'TECHNOLOGY', 'AAA', 97.8000, false);

INSERT INTO orders (id, order_ref, cusip, portfolio, trader, side, order_type, time_in_force, quantity, limit_price, status, filled_quantity, avg_fill_price, status_reason, created_at, updated_at, version) VALUES
  (1, 'ord-0001', '912828XG8', 'RATES-A',  'alice', 'BUY',  'MARKET', 'DAY', 1000000.00, NULL,     'FILLED',            1000000.00, 98.5600,  NULL,                        '2026-01-05T14:30:00Z', '2026-01-05T14:30:02Z', 2),
  (2, 'ord-0002', '037833EM5', 'CREDIT-A', 'bob',   'SELL', 'LIMIT',  'GTC', 500000.00,  101.3000, 'PARTIALLY_FILLED',  300000.00,  101.2800, NULL,                        '2026-01-05T15:00:00Z', '2026-01-05T15:05:00Z', 3),
  (3, 'ord-0003', '594918BW3', 'RATES-A',  'alice', 'BUY',  'LIMIT',  'DAY', 2000000.00, 97.7500,  'NEW',               0.00,       NULL,     NULL,                        '2026-01-06T09:15:00Z', '2026-01-06T09:15:00Z', 1),
  (4, 'ord-0004', '912828XG8', 'CREDIT-A', 'carol', 'SELL', 'MARKET', 'IOC', 750000.00,  NULL,     'FILLED',            750000.00,  98.6000,  NULL,                        '2026-01-06T10:00:00Z', '2026-01-06T10:00:01Z', 2),
  (5, 'ord-0005', '037833EM5', 'RATES-A',  'bob',   'BUY',  'LIMIT',  'DAY', 1000000.00, 100.0000, 'REJECTED',          0.00,       NULL,     'Limit too far from market', '2026-01-06T11:00:00Z', '2026-01-06T11:00:00Z', 1),
  (6, 'ord-0006', '594918BW3', 'CREDIT-A', 'alice', 'BUY',  'MARKET', 'DAY', 250000.00,  NULL,     'FILLED',            250000.00,  97.8500,  NULL,                        '2026-01-07T13:20:00Z', '2026-01-07T13:20:03Z', 2),
  (7, 'ord-0007', '912828XG8', 'RATES-A',  'carol', 'SELL', 'LIMIT',  'GTC', 1500000.00, 98.5000,  'CANCELLED',         0.00,       NULL,     'Trader cancelled',          '2026-01-07T14:00:00Z', '2026-01-07T14:30:00Z', 2),
  (8, 'ord-0008', '037833EM5', 'CREDIT-A', 'bob',   'BUY',  'MARKET', 'DAY', 600000.00,  NULL,     'FILLED',            600000.00,  101.3500, NULL,                        '2026-01-07T15:45:00Z', '2026-01-07T15:45:02Z', 2);

-- Executions reconcile exactly to each order's filled_quantity (order 1 is a two-venue fill).
INSERT INTO execution (id, order_id, quantity, price, venue, executed_at) VALUES
  (1, 1, 600000.00, 98.5400,  'TRADEWEB',    '2026-01-05T14:30:01Z'),
  (2, 1, 400000.00, 98.5650,  'BLOOMBERG',   '2026-01-05T14:30:02Z'),
  (3, 2, 300000.00, 101.2800, 'MARKETAXESS', '2026-01-05T15:05:00Z'),
  (4, 4, 750000.00, 98.6000,  'TRADEWEB',    '2026-01-06T10:00:01Z'),
  (5, 6, 250000.00, 97.8500,  'BLOOMBERG',   '2026-01-07T13:20:03Z'),
  (6, 8, 600000.00, 101.3500, 'MARKETAXESS', '2026-01-07T15:45:02Z');

-- Realign the identity sequences past the explicit ids we inserted (defensive; dbt does not write here).
SELECT setval(pg_get_serial_sequence('orders', 'id'), (SELECT max(id) FROM orders));
SELECT setval(pg_get_serial_sequence('execution', 'id'), (SELECT max(id) FROM execution));
